name: sentilife
description: "SentiLife — Fall detection and monitoring application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.9
  http: ^1.2.2
  intl: any

  # Auto-actualización
  package_info_plus: ^10.2.0
  dio: ^5.10.0
  open_filex: ^4.7.0
  path_provider: ^2.1.6
  sensors_plus: ^7.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
