name: proyecto_flutter
description: "Fall Detector Tester application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  http: ^1.2.2

  # Firebase
  firebase_core: ^4.11.0

  # Auto-actualización
  package_info_plus: ^10.2.0   # leer versionCode instalado
  dio: ^5.10.0                  # descarga con progreso + timeouts
  open_filex: ^4.7.0            # lanzar instalador nativo
  path_provider: ^2.1.6         # ruta de descarga del APK

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
